version: '3'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    networks:
      - mynetwork

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    networks:
      - mynetwork
    depends_on:
      - db

  db:
    build:
      context: ./db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
